# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):

    def open_login_window(self):
        from login_window import Ui_LoginWindow
        self.LoginWindow = QtWidgets.QMainWindow()
        self.ui = Ui_LoginWindow()
        self.ui.setupUi(self.LoginWindow)
        self.LoginWindow.show()

    def open_sign_in_window(self):
        from sign_in_window import Ui_SigninWindow
        self.SigninWindow = QtWidgets.QMainWindow()
        self.ui = Ui_SigninWindow()
        self.ui.setupUi(self.SigninWindow)
        self.SigninWindow.show()

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1192, 669)
        MainWindow.setStyleSheet("background-color:rgb(255, 255, 255);\n"
                                 "")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setObjectName("verticalWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.verticalWidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.image_main = QtWidgets.QLabel(self.verticalWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored,
                                           QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.image_main.sizePolicy().hasHeightForWidth())
        self.image_main.setSizePolicy(sizePolicy)
        self.image_main.setMinimumSize(QtCore.QSize(631, 471))
        self.image_main.setMaximumSize(QtCore.QSize(631, 471))
        self.image_main.setAutoFillBackground(False)
        self.image_main.setStyleSheet("")
        self.image_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.image_main.setText("")
        self.image_main.setTextFormat(QtCore.Qt.PlainText)
        self.image_main.setPixmap(
            QtGui.QPixmap(":/main/undraw_web_shopping_re_owap.png"))
        self.image_main.setScaledContents(True)
        self.image_main.setAlignment(QtCore.Qt.AlignCenter)
        self.image_main.setWordWrap(False)
        self.image_main.setOpenExternalLinks(False)
        self.image_main.setObjectName("image_main")
        self.gridLayout_2.addWidget(self.image_main, 0, 0, 1, 1)
        self.button_slide = QtWidgets.QWidget(self.verticalWidget)
        self.button_slide.setMinimumSize(QtCore.QSize(631, 101))
        self.button_slide.setMaximumSize(QtCore.QSize(631, 101))
        self.button_slide.setObjectName("button_slide")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.button_slide)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridWidget = QtWidgets.QWidget(self.button_slide)
        self.gridWidget.setObjectName("gridWidget")
        self.button_slide_in = QtWidgets.QGridLayout(self.gridWidget)
        self.button_slide_in.setObjectName("button_slide_in")
        self.button_group = QtWidgets.QWidget(self.gridWidget)
        self.button_group.setMinimumSize(QtCore.QSize(421, 81))
        self.button_group.setMaximumSize(QtCore.QSize(421, 81))
        self.button_group.setObjectName("button_group")
        self.gridLayout = QtWidgets.QGridLayout(self.button_group)
        self.gridLayout.setContentsMargins(1, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.sign_up = QtWidgets.QPushButton(self.button_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.sign_up.sizePolicy().hasHeightForWidth())
        self.sign_up.setSizePolicy(sizePolicy)
        self.sign_up.setMinimumSize(QtCore.QSize(166, 49))
        self.sign_up.setMaximumSize(QtCore.QSize(166, 49))
        self.sign_up.setStyleSheet("QPushButton {\n"
                                   "    background-color:#3f3d56;\n"
                                   "    font: 9pt \"Eras Medium ITC\";\n"
                                   "    color:white;\n"
                                   "    border-style: outset;\n"
                                   "    border-width: 2px;\n"
                                   "    border-radius: 20px;\n"
                                   "    border-color: beige;\n"
                                   "\n"
                                   "    }\n"
                                   "\n"
                                   "QPushButton:hover {\n"
                                   "    background-color:#e6e6e6;\n"
                                   "    color:#3f3d56;\n"
                                   "    border-color:#3f3d56;\n"
                                   "    border-style:solid;\n"
                                   "    font-weight:bold;\n"
                                   "}")
        self.sign_up.setAutoDefault(False)
        self.sign_up.setDefault(False)
        self.sign_up.setFlat(False)
        self.sign_up.setObjectName("sign_up")
        self.gridLayout.addWidget(self.sign_up, 0, 1, 1, 1)
        self.log_in = QtWidgets.QPushButton(self.button_group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored,
                                           QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.log_in.sizePolicy().hasHeightForWidth())
        self.log_in.setSizePolicy(sizePolicy)
        self.log_in.setMinimumSize(QtCore.QSize(167, 49))
        self.log_in.setMaximumSize(QtCore.QSize(167, 49))
        self.log_in.setStyleSheet("QPushButton {\n"
                                  "    background-color:#564fcc;\n"
                                  "    font: 9pt \"Eras Medium ITC\";\n"
                                  "    color:white;\n"
                                  "    border-style: outset;\n"
                                  "    border-width: 2px;\n"
                                  "    border-radius: 20px;\n"
                                  "    border-color: beige;\n"
                                  "\n"
                                  "    }\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    background-color:rgb(230, 230, 230);\n"
                                  "    color:#6c63ff;\n"
                                  "    border-color:#6c63ff;\n"
                                  "    border-style:solid;\n"
                                  "    font-weight:bold;\n"
                                  "}")
        self.log_in.setObjectName("log_in")
        self.gridLayout.addWidget(self.log_in, 0, 2, 1, 1)
        self.button_slide_in.addWidget(self.button_group, 0, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.gridWidget)
        self.gridLayout_2.addWidget(self.button_slide, 1, 0, 1, 1)
        self.horizontalLayout_3.addWidget(self.verticalWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
        
        self.sign_up.clicked.connect(self.open_sign_in_window)
        self.sign_up.clicked.connect(MainWindow.close)
        self.log_in.clicked.connect(self.open_login_window)
        self.log_in.clicked.connect(MainWindow.close)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.sign_up.setText(_translate("MainWindow", "Sign up"))
        self.log_in.setText(_translate("MainWindow", "Log in"))


import qrc_img

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
