# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment_dialogue_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Payment_dialogue_Window(object):

    def setupUi(self, Payment_dialogue_Window):
        Payment_dialogue_Window.setObjectName("Payment_dialogue_Window")
        Payment_dialogue_Window.resize(451, 472)
        Payment_dialogue_Window.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(Payment_dialogue_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setMinimumSize(QtCore.QSize(433, 428))
        self.verticalWidget.setMaximumSize(QtCore.QSize(433, 428))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setMinimumSize(QtCore.QSize(431, 311))
        self.label.setMaximumSize(QtCore.QSize(431, 311))
        self.label.setStyleSheet("background-image: url(:/sign_in_dialogue/undraw_Happy_announcement_re_tsm0.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/success pay/undraw_Credit_card_re_blml.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.output_message = QtWidgets.QLabel(self.verticalWidget)
        self.output_message.setMinimumSize(QtCore.QSize(400, 50))
        self.output_message.setMaximumSize(QtCore.QSize(400, 50))
        self.output_message.setStyleSheet("QLabel {\n"
        "    font: 10pt \"Eras Medium ITC\";\n"
        "    }")
        self.output_message.setObjectName("output_message")
        self.gridLayout_2.addWidget(self.output_message, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ok = QtWidgets.QPushButton(self.verticalWidget,clicked=lambda:self.ok_click(Payment_dialogue_Window))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setMinimumSize(QtCore.QSize(167, 49))
        self.ok.setMaximumSize(QtCore.QSize(167, 49))
        self.ok.setStyleSheet("QPushButton {\n"
        "    background-color:#564fcc;\n"
        "    font: 10pt \"Eras Medium ITC\";\n"
        "    color:white;\n"
        "    border-style: outset;\n"
        "    border-width: 3px;\n"
        "    border-radius: 20px;\n"
        "    border-color: beige;\n"
        "\n"
        "    }\n"
        "\n"
        "QPushButton:hover {\n"
        "    background-color:#f2f2f2;\n"
        "    color:#6c63ff;\n"
        "    border-color:#6c63ff;\n"
        "    border-style:outset;\n"
        "    font-weight:bold;\n"
        "}")
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.verticalWidget, 0, 0, 1, 1)
        Payment_dialogue_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Payment_dialogue_Window)
        self.statusbar.setObjectName("statusbar")
        Payment_dialogue_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Payment_dialogue_Window)
        QtCore.QMetaObject.connectSlotsByName(Payment_dialogue_Window)

    def retranslateUi(self, Payment_dialogue_Window):
        _translate = QtCore.QCoreApplication.translate
        Payment_dialogue_Window.setWindowTitle(_translate("Payment_dialogue_Window", "MainWindow"))
        self.output_message.setText(_translate("Payment_dialogue_Window", "<html><head/><body><p align=\"center\">Your Payment done successfuly !</p></body></html>"))
        self.ok.setText(_translate("Payment_dialogue_Window", "Ok"))

    def ok_click(self, Payment_dialogue_Window):

        from store_window import Ui_StoreWindow
        self.StoreWindow = QtWidgets.QMainWindow()
        self.ui = Ui_StoreWindow()
        self.ui.setupUi(self.StoreWindow)
        self.StoreWindow.show()

        Payment_dialogue_Window.close()



import qrc_img


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Payment_dialogue_Window = QtWidgets.QMainWindow()
    ui = Ui_Payment_dialogue_Window()
    ui.setupUi(Payment_dialogue_Window)
    Payment_dialogue_Window.show()
    sys.exit(app.exec_())
