# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'payment_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PaymentWindow(object):

    def setupUi(self, PaymentWindow):
        PaymentWindow.setObjectName("PaymentWindow")
        PaymentWindow.setWindowModality(QtCore.Qt.NonModal)
        PaymentWindow.resize(1083, 643)
        PaymentWindow.setStyleSheet("background-color:white\n"
                                    ";")
        self.centralwidget = QtWidgets.QWidget(PaymentWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.sign_in_title = QtWidgets.QLabel(self.centralwidget)
        self.sign_in_title.setMinimumSize(QtCore.QSize(0, 110))
        self.sign_in_title.setMaximumSize(QtCore.QSize(16777215, 110))
        self.sign_in_title.setStyleSheet(
            "QLabel {\n"
            "    background-color:#6c63ff;\n"
            "    font: 22pt \"Eras Medium ITC\";\n"
            "    color:white;\n"
            "\n"
            "    }\n"
            "")
        self.sign_in_title.setObjectName("sign_in_title")
        self.verticalLayout_9.addWidget(self.sign_in_title)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.verticalWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_4.setMinimumSize(QtCore.QSize(411, 108))
        self.verticalWidget_4.setMaximumSize(QtCore.QSize(411, 108))
        self.verticalWidget_4.setObjectName("verticalWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalWidget_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.verticalWidget_4)
        self.label_7.setMinimumSize(QtCore.QSize(161, 50))
        self.label_7.setMaximumSize(QtCore.QSize(161, 50))
        self.label_7.setStyleSheet("\n"
                                   "    font: 12pt \"Eras Medium ITC\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_4.addWidget(self.label_7)
        self.Product_name = QtWidgets.QTextBrowser(self.verticalWidget_4)
        self.Product_name.setMinimumSize(QtCore.QSize(400, 50))
        self.Product_name.setMaximumSize(QtCore.QSize(400, 50))
        self.Product_name.setAutoFillBackground(False)
        self.Product_name.setStyleSheet("\n"
                                        "    padding-left:10px;\n"
                                        "    background-color:white;\n"
                                        "    font: 12pt \"Eras Medium ITC\";\n"
                                        "    color:2f2e41;\n"
                                        "    border-style: solid;\n"
                                        "    border-width: 2px;\n"
                                        "    border-radius: 10px;\n"
                                        "    border-color:#cccccc;\n"
                                        "\n"
                                        "\n"
                                        "    border-style:solid;\n"
                                        "")
        self.Product_name.setInputMethodHints(QtCore.Qt.ImhNone)
        self.Product_name.setLineWidth(1)
        self.Product_name.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.Product_name.setTabChangesFocus(False)
        self.Product_name.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.Product_name.setLineWrapColumnOrWidth(0)
        self.Product_name.setMarkdown("")
        self.Product_name.setObjectName("Product_name")
        self.verticalLayout_4.addWidget(self.Product_name)
        self.verticalLayout_7.addWidget(self.verticalWidget_4)
        self.verticalWidget_3 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_3.setMinimumSize(QtCore.QSize(411, 108))
        self.verticalWidget_3.setMaximumSize(QtCore.QSize(411, 108))
        self.verticalWidget_3.setObjectName("verticalWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalWidget_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.verticalWidget_3)
        self.label_6.setMinimumSize(QtCore.QSize(161, 50))
        self.label_6.setMaximumSize(QtCore.QSize(161, 50))
        self.label_6.setStyleSheet("\n"
                                   "    font: 12pt \"Eras Medium ITC\";")
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.product_price = QtWidgets.QTextBrowser(self.verticalWidget_3)
        self.product_price.setMinimumSize(QtCore.QSize(400, 50))
        self.product_price.setMaximumSize(QtCore.QSize(400, 50))
        self.product_price.setAutoFillBackground(False)
        self.product_price.setStyleSheet(
            "\n"
            "    padding-left:10px;\n"
            "    background-color:white;\n"
            "    font: 12pt \"Eras Medium ITC\";\n"
            "    color:2f2e41;\n"
            "    border-style: solid;\n"
            "    border-width: 2px;\n"
            "    border-radius: 10px;\n"
            "    border-color:#cccccc;\n"
            "\n"
            "\n"
            "    border-style:solid;\n"
            "")
        self.product_price.setInputMethodHints(QtCore.Qt.ImhNone)
        self.product_price.setLineWidth(1)
        self.product_price.setAutoFormatting(
            QtWidgets.QTextEdit.AutoBulletList)
        self.product_price.setTabChangesFocus(False)
        self.product_price.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.product_price.setLineWrapColumnOrWidth(0)
        self.product_price.setMarkdown("")
        self.product_price.setObjectName("product_price")
        self.verticalLayout_3.addWidget(self.product_price)
        self.verticalLayout_7.addWidget(self.verticalWidget_3)
        spacerItem = QtWidgets.QSpacerItem(20, 40,
                                           QtWidgets.QSizePolicy.Minimum,
                                           QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem)
        self.verticalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_2.setMinimumSize(QtCore.QSize(411, 108))
        self.verticalWidget_2.setMaximumSize(QtCore.QSize(411, 108))
        self.verticalWidget_2.setObjectName("verticalWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.verticalWidget_2)
        self.label_4.setMinimumSize(QtCore.QSize(161, 50))
        self.label_4.setMaximumSize(QtCore.QSize(161, 50))
        self.label_4.setStyleSheet("\n"
                                   "    font: 12pt \"Eras Medium ITC\";")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.total_price = QtWidgets.QTextBrowser(self.verticalWidget_2)
        self.total_price.setMinimumSize(QtCore.QSize(400, 50))
        self.total_price.setMaximumSize(QtCore.QSize(400, 50))
        self.total_price.setAutoFillBackground(False)
        self.total_price.setStyleSheet("\n"
                                       "    padding-left:10px;\n"
                                       "    background-color:white;\n"
                                       "    font: 12pt \"Eras Medium ITC\";\n"
                                       "    color:2f2e41;\n"
                                       "    border-style: solid;\n"
                                       "    border-width: 2px;\n"
                                       "    border-radius: 10px;\n"
                                       "    border-color:#cccccc;\n"
                                       "\n"
                                       "\n"
                                       "    border-style:solid;\n"
                                       "")
        self.total_price.setInputMethodHints(QtCore.Qt.ImhNone)
        self.total_price.setLineWidth(1)
        self.total_price.setAutoFormatting(QtWidgets.QTextEdit.AutoBulletList)
        self.total_price.setTabChangesFocus(False)
        self.total_price.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.total_price.setLineWrapColumnOrWidth(0)
        self.total_price.setReadOnly(True)
        self.total_price.setMarkdown("")
        self.total_price.setOpenExternalLinks(False)
        self.total_price.setObjectName("total_price")
        self.verticalLayout_2.addWidget(self.total_price)
        self.verticalLayout_7.addWidget(self.verticalWidget_2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        spacerItem1 = QtWidgets.QSpacerItem(47, 20,
                                            QtWidgets.QSizePolicy.Fixed,
                                            QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalWidget_2.setMinimumSize(QtCore.QSize(411, 80))
        self.horizontalWidget_2.setMaximumSize(QtCore.QSize(411, 80))
        self.horizontalWidget_2.setObjectName("horizontalWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(
            self.horizontalWidget_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.horizontalWidget_2)
        self.label.setStyleSheet("font: 12pt \"Eras Medium ITC\";")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.quantity = QtWidgets.QSpinBox(self.horizontalWidget_2)
        self.quantity.setValue(1)
        self.quantity.valueChanged.connect(self.add_quantity)
        self.quantity.setMinimumSize(QtCore.QSize(91, 50))
        self.quantity.setMaximumSize(QtCore.QSize(91, 50))
        self.quantity.setStyleSheet("\n"
                                    "    padding-left:10px;\n"
                                    "    background-color:white;\n"
                                    "    font: 9pt \"Eras Medium ITC\";\n"
                                    "    color:2f2e41;\n"
                                    "    border-style: solid;\n"
                                    "    border-width: 2px;\n"
                                    "    border-color:#cccccc;\n"
                                    "\n"
                                    "    ")
        self.quantity.setWrapping(False)
        self.quantity.setObjectName("quantity")
        self.horizontalLayout_2.addWidget(self.quantity)
        self.gridLayout_7.addWidget(self.horizontalWidget_2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem2, 0, 0, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_7)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalWidget_5 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_5.setMinimumSize(QtCore.QSize(191, 361))
        self.verticalWidget_5.setMaximumSize(QtCore.QSize(191, 361))
        self.verticalWidget_5.setObjectName("verticalWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalWidget_5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.debit = QtWidgets.QPushButton(self.verticalWidget_5)
        self.debit.clicked.connect(PaymentWindow.close)
        self.debit.clicked.connect(self.debit_click)
        self.debit.setMinimumSize(QtCore.QSize(171, 41))
        self.debit.setMaximumSize(QtCore.QSize(171, 41))
        self.debit.setStyleSheet("QPushButton {\n"
                                 "    background-color:#f9f9f9;\n"
                                 "    font: 10pt \"Eras Medium ITC\";\n"
                                 "    color:#6c63ff;\n"
                                 "    border-style: outset;\n"
                                 "    border-width: 3px;\n"
                                 "    border-radius: 20px;\n"
                                 "    font-weight:bold;\n"
                                 "    border-color:#6c63ff;\n"
                                 "\n"
                                 "    }\n"
                                 "\n"
                                 "QPushButton:hover {\n"
                                 "    background-color:#6c63ff;\n"
                                 "    color:#f9f9f9;\n"
                                 "    border-color:#6c63ff;\n"
                                 "    border-style:solide;\n"
                                 "    font-weight:bold;\n"
                                 "}")
        self.debit.setObjectName("debit")
        self.gridLayout_3.addWidget(self.debit, 1, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_8 = QtWidgets.QLabel(self.verticalWidget_5)
        self.label_8.setMinimumSize(QtCore.QSize(171, 241))
        self.label_8.setMaximumSize(QtCore.QSize(171, 241))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/debit/debit.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.horizontalLayout.addWidget(self.verticalWidget_5)
        self.verticalWidget_6 = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget_6.setMinimumSize(QtCore.QSize(191, 361))
        self.verticalWidget_6.setMaximumSize(QtCore.QSize(191, 361))
        self.verticalWidget_6.setObjectName("verticalWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalWidget_6)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_9 = QtWidgets.QLabel(self.verticalWidget_6)
        self.label_9.setMinimumSize(QtCore.QSize(171, 241))
        self.label_9.setMaximumSize(QtCore.QSize(171, 241))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap(":/credit/credit.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_6.addWidget(self.label_9, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem4, 1, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        self.credit = QtWidgets.QPushButton(self.verticalWidget_6)
        self.credit.clicked.connect(PaymentWindow.close)
        self.credit.clicked.connect(self.credit_click)
        self.credit.setMinimumSize(QtCore.QSize(171, 41))
        self.credit.setMaximumSize(QtCore.QSize(171, 41))
        self.credit.setStyleSheet("QPushButton {\n"
                                  "    background-color:#f9f9f9;\n"
                                  "    font: 10pt \"Eras Medium ITC\";\n"
                                  "    color:#6c63ff;\n"
                                  "    border-style: outset;\n"
                                  "    border-width: 3px;\n"
                                  "    border-radius: 20px;\n"
                                  "    font-weight:bold;\n"
                                  "    border-color:#6c63ff;\n"
                                  "\n"
                                  "    }\n"
                                  "\n"
                                  "QPushButton:hover {\n"
                                  "    background-color:#6c63ff;\n"
                                  "    color:#f9f9f9;\n"
                                  "    border-color:#6c63ff;\n"
                                  "    border-style:solide;\n"
                                  "    font-weight:bold;\n"
                                  "}")
        self.credit.setObjectName("credit")
        self.gridLayout_5.addWidget(self.credit, 1, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_5)
        self.horizontalLayout.addWidget(self.verticalWidget_6)
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setMinimumSize(QtCore.QSize(191, 361))
        self.verticalWidget.setMaximumSize(QtCore.QSize(191, 361))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalWidget)
        self.label_3.setMinimumSize(QtCore.QSize(171, 241))
        self.label_3.setMaximumSize(QtCore.QSize(171, 241))
        self.label_3.setText("")
        self.label_3.setPixmap(
            QtGui.QPixmap(":/cash/undraw_Wallet_re_cx9u.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem5, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.cash = QtWidgets.QPushButton(self.verticalWidget)
        self.cash.clicked.connect(self.cash_click)
        self.cash.clicked.connect(PaymentWindow.close)
        self.cash.setMinimumSize(QtCore.QSize(171, 41))
        self.cash.setMaximumSize(QtCore.QSize(171, 41))
        self.cash.setStyleSheet("QPushButton {\n"
                                "    background-color:#f9f9f9;\n"
                                "    font: 10pt \"Eras Medium ITC\";\n"
                                "    color:#6c63ff;\n"
                                "    border-style: outset;\n"
                                "    border-width: 3px;\n"
                                "    border-radius: 20px;\n"
                                "    font-weight:bold;\n"
                                "    border-color:#6c63ff;\n"
                                "\n"
                                "    }\n"
                                "\n"
                                "QPushButton:hover {\n"
                                "    background-color:#6c63ff;\n"
                                "    color:#f9f9f9;\n"
                                "    border-color:#6c63ff;\n"
                                "    border-style:solide;\n"
                                "    font-weight:bold;\n"
                                "}")
        self.cash.setObjectName("cash")
        self.gridLayout.addWidget(self.cash, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout.addWidget(self.verticalWidget)
        self.verticalLayout_8.addLayout(self.horizontalLayout)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40,
                                            QtWidgets.QSizePolicy.Minimum,
                                            QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem6)
        self.gridLayout_8.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        PaymentWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(PaymentWindow)
        QtCore.QMetaObject.connectSlotsByName(PaymentWindow)

        self.fill_info()
        

    def retranslateUi(self, PaymentWindow):
        _translate = QtCore.QCoreApplication.translate
        PaymentWindow.setWindowTitle(_translate("PaymentWindow", "MainWindow"))
        self.sign_in_title.setText(
            _translate(
                "PaymentWindow",
                "<html><head/><body><p align=\"center\">Payment page</p></body></html>"
            ))
        self.label_7.setText(_translate("PaymentWindow", "Product name :"))
        self.Product_name.setHtml(
            _translate(
                "PaymentWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"
            ))
        self.label_6.setText(_translate("PaymentWindow", "Price per unite :"))
        self.product_price.setHtml(
            _translate(
                "PaymentWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"
            ))
        self.label_4.setText(_translate("PaymentWindow", "Total :"))
        self.total_price.setHtml(
            _translate(
                "PaymentWindow",
                "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
                "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
                "p, li { white-space: pre-wrap; }\n"
                "</style></head><body style=\" font-family:\'Eras Medium ITC\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
                "<p style=\"-qt-paragraph-type:empty; margin-top:8px; margin-bottom:8px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"
            ))
        self.label.setText(
            _translate("PaymentWindow", "Choose your quantity :"))
        self.debit.setText(_translate("PaymentWindow", "Debit card"))
        self.credit.setText(_translate("PaymentWindow", "Credit card"))
        self.cash.setText(_translate("PaymentWindow", "Cash on Delivery"))

    def fill_info(self):

        with open("py/Cache_File.txt", "r") as cache_file:

            lines = cache_file.readlines()

        cache_list = []

        for line in lines:

            cache_list.append(line.strip())

        for combo in cache_list:

            values = combo.strip().split(',')
            username = values[0]
            product = values[1]
            price_per_unite = values[2]

            self.Product_name.setText(product)
            self.product_price.setText(price_per_unite)
            self.total_price.setText(price_per_unite)

    def add_quantity(self):

        price = self.product_price.toPlainText()
        int_price = int(price[2:].strip())

        total = ((int_price) * int(self.quantity.text()))
        self.total_price.setText(str(total))

    def save_cache(self, payment_methode):

        payment_cache = payment_methode
        quantity_cache = str(self.quantity.value())
        total_price_cache = (("$") + str(self.total_price.toPlainText()))

        with open('py/Cache_File.txt') as cache_file:

            lines = cache_file.readlines()

            cache_list = []

        for line in lines:

            cache_list.append(line.strip())

        for combo in range(len(cache_list)):

            cache = cache_list[combo].split(",")

            cache[3] = quantity_cache
            cache[4] = payment_cache
            cache[5] = total_price_cache

            cache_list[combo] = ",".join(cache)

        with open('py/Cache_File.txt', 'w') as cache_file:

            for item in cache_list:

                cache_file.write(item + '\n')

    def credit_click(self):

        Payment_methode = "credit-card"
        self.save_cache(Payment_methode)

        from transaction_window import Ui_transaction_window
        self.transaction_window = QtWidgets.QMainWindow()
        self.ui = Ui_transaction_window()
        self.ui.setupUi(self.transaction_window)
        self.transaction_window.show()

    def debit_click(self):

        Payment_methode = "debit-card"
        self.save_cache(Payment_methode)

        from transaction_window import Ui_transaction_window
        self.transaction_window = QtWidgets.QMainWindow()
        self.ui = Ui_transaction_window()
        self.ui.setupUi(self.transaction_window)
        self.transaction_window.show()

    def cash_click(self):

        Payment_methode = "cash on delivery"
        self.save_cache(Payment_methode)

        from transaction_window import Ui_transaction_window
        self.transaction_window = QtWidgets.QMainWindow()
        self.ui = Ui_transaction_window()
        self.ui.setupUi(self.transaction_window)
        self.transaction_window.show()

    # def closeEvent(self):
        
    #     from store_window import Ui_StoreWindow
    #     self.StoreWindow = QtWidgets.QMainWindow()
    #     self.ui = Ui_StoreWindow()
    #     self.ui.setupUi(self.StoreWindow)
    #     self.StoreWindow.show()

import qrc_img

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    PaymentWindow = QtWidgets.QMainWindow()
    ui = Ui_PaymentWindow()
    ui.setupUi(PaymentWindow)
    PaymentWindow.show()
    sys.exit(app.exec_())
