# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'product_dialogue_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Product_dialogue_Window(object):
    
    def setupUi(self, Product_dialogue_Window):
        Product_dialogue_Window.setObjectName("Product_dialogue_Window")
        Product_dialogue_Window.resize(451, 472)
        Product_dialogue_Window.setStyleSheet("background-color:white;")
        self.centralwidget = QtWidgets.QWidget(Product_dialogue_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalWidget.setMinimumSize(QtCore.QSize(433, 428))
        self.verticalWidget.setMaximumSize(QtCore.QSize(433, 428))
        self.verticalWidget.setObjectName("verticalWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalWidget)
        self.label.setMinimumSize(QtCore.QSize(431, 311))
        self.label.setMaximumSize(QtCore.QSize(431, 311))
        self.label.setStyleSheet("background-image: url(:/sign_in_dialogue/undraw_Happy_announcement_re_tsm0.png);")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/database/undraw_Folder_files_re_2cbm.png"))
        self.label.setScaledContents(True)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.output_message = QtWidgets.QLabel(self.verticalWidget)
        self.output_message.setMinimumSize(QtCore.QSize(400, 50))
        self.output_message.setMaximumSize(QtCore.QSize(400, 50))
        self.output_message.setStyleSheet("QLabel {\n"
"    font: 10pt \"Eras Medium ITC\";\n"
"    }")
        self.output_message.setObjectName("output_message")
        self.gridLayout_2.addWidget(self.output_message, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.ok = QtWidgets.QPushButton(self.verticalWidget)
        self.ok.clicked.connect(Product_dialogue_Window.close)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ok.sizePolicy().hasHeightForWidth())
        self.ok.setSizePolicy(sizePolicy)
        self.ok.setMinimumSize(QtCore.QSize(167, 49))
        self.ok.setMaximumSize(QtCore.QSize(167, 49))
        self.ok.setStyleSheet("QPushButton {\n"
"    background-color:#564fcc;\n"
"    font: 10pt \"Eras Medium ITC\";\n"
"    color:white;\n"
"    border-style: outset;\n"
"    border-width: 3px;\n"
"    border-radius: 20px;\n"
"    border-color: beige;\n"
"\n"
"    }\n"
"\n"
"QPushButton:hover {\n"
"    background-color:#f2f2f2;\n"
"    color:#6c63ff;\n"
"    border-color:#6c63ff;\n"
"    border-style:outset;\n"
"    font-weight:bold;\n"
"}")
        self.ok.setObjectName("ok")
        self.gridLayout.addWidget(self.ok, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3.addWidget(self.verticalWidget, 0, 0, 1, 1)
        Product_dialogue_Window.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Product_dialogue_Window)
        self.statusbar.setObjectName("statusbar")
        Product_dialogue_Window.setStatusBar(self.statusbar)

        self.retranslateUi(Product_dialogue_Window)
        QtCore.QMetaObject.connectSlotsByName(Product_dialogue_Window)

    def retranslateUi(self, Product_dialogue_Window):
        _translate = QtCore.QCoreApplication.translate
        Product_dialogue_Window.setWindowTitle(_translate("Product_dialogue_Window", "MainWindow"))
        self.output_message.setText(_translate("Product_dialogue_Window", "<html><head/><body><p align=\"center\">Your Product is now in the Database !</p></body></html>"))
        self.ok.setText(_translate("Product_dialogue_Window", "Ok"))


import qrc_img

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Product_dialogue_Window = QtWidgets.QMainWindow()
    ui = Ui_Product_dialogue_Window()
    ui.setupUi(Product_dialogue_Window)
    Product_dialogue_Window.show()
    sys.exit(app.exec_())
